# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_delta_robot/linear_speed_xyz.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class linear_speed_xyz(genpy.Message):
  _md5sum = "8043196b03be66e3bcd2ba1e7c560f64"
  _type = "my_delta_robot/linear_speed_xyz"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 xo
float32 yo
float32 zo
float32 xf
float32 yf
float32 zf
float32 vmax
float32 amax
int64 gripper"""
  __slots__ = ['xo','yo','zo','xf','yf','zf','vmax','amax','gripper']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       xo,yo,zo,xf,yf,zf,vmax,amax,gripper

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(linear_speed_xyz, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.xo is None:
        self.xo = 0.
      if self.yo is None:
        self.yo = 0.
      if self.zo is None:
        self.zo = 0.
      if self.xf is None:
        self.xf = 0.
      if self.yf is None:
        self.yf = 0.
      if self.zf is None:
        self.zf = 0.
      if self.vmax is None:
        self.vmax = 0.
      if self.amax is None:
        self.amax = 0.
      if self.gripper is None:
        self.gripper = 0
    else:
      self.xo = 0.
      self.yo = 0.
      self.zo = 0.
      self.xf = 0.
      self.yf = 0.
      self.zf = 0.
      self.vmax = 0.
      self.amax = 0.
      self.gripper = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8fq().pack(_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.gripper,) = _get_struct_8fq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8fq().pack(_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.gripper,) = _get_struct_8fq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8fq = None
def _get_struct_8fq():
    global _struct_8fq
    if _struct_8fq is None:
        _struct_8fq = struct.Struct("<8fq")
    return _struct_8fq
