// Generated by gencpp from file my_delta_robot/linear_speed_xyz.msg
// DO NOT EDIT!


#ifndef MY_DELTA_ROBOT_MESSAGE_LINEAR_SPEED_XYZ_H
#define MY_DELTA_ROBOT_MESSAGE_LINEAR_SPEED_XYZ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_delta_robot
{
template <class ContainerAllocator>
struct linear_speed_xyz_
{
  typedef linear_speed_xyz_<ContainerAllocator> Type;

  linear_speed_xyz_()
    : xo(0.0)
    , yo(0.0)
    , zo(0.0)
    , xf(0.0)
    , yf(0.0)
    , zf(0.0)
    , vmax(0.0)
    , amax(0.0)
    , gripper(0)  {
    }
  linear_speed_xyz_(const ContainerAllocator& _alloc)
    : xo(0.0)
    , yo(0.0)
    , zo(0.0)
    , xf(0.0)
    , yf(0.0)
    , zf(0.0)
    , vmax(0.0)
    , amax(0.0)
    , gripper(0)  {
  (void)_alloc;
    }



   typedef float _xo_type;
  _xo_type xo;

   typedef float _yo_type;
  _yo_type yo;

   typedef float _zo_type;
  _zo_type zo;

   typedef float _xf_type;
  _xf_type xf;

   typedef float _yf_type;
  _yf_type yf;

   typedef float _zf_type;
  _zf_type zf;

   typedef float _vmax_type;
  _vmax_type vmax;

   typedef float _amax_type;
  _amax_type amax;

   typedef int64_t _gripper_type;
  _gripper_type gripper;





  typedef boost::shared_ptr< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> const> ConstPtr;

}; // struct linear_speed_xyz_

typedef ::my_delta_robot::linear_speed_xyz_<std::allocator<void> > linear_speed_xyz;

typedef boost::shared_ptr< ::my_delta_robot::linear_speed_xyz > linear_speed_xyzPtr;
typedef boost::shared_ptr< ::my_delta_robot::linear_speed_xyz const> linear_speed_xyzConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator1> & lhs, const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator2> & rhs)
{
  return lhs.xo == rhs.xo &&
    lhs.yo == rhs.yo &&
    lhs.zo == rhs.zo &&
    lhs.xf == rhs.xf &&
    lhs.yf == rhs.yf &&
    lhs.zf == rhs.zf &&
    lhs.vmax == rhs.vmax &&
    lhs.amax == rhs.amax &&
    lhs.gripper == rhs.gripper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator1> & lhs, const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_delta_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8043196b03be66e3bcd2ba1e7c560f64";
  }

  static const char* value(const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8043196b03be66e3ULL;
  static const uint64_t static_value2 = 0xbcd2ba1e7c560f64ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_delta_robot/linear_speed_xyz";
  }

  static const char* value(const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 xo\n"
"float32 yo\n"
"float32 zo\n"
"float32 xf\n"
"float32 yf\n"
"float32 zf\n"
"float32 vmax\n"
"float32 amax\n"
"int64 gripper\n"
;
  }

  static const char* value(const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xo);
      stream.next(m.yo);
      stream.next(m.zo);
      stream.next(m.xf);
      stream.next(m.yf);
      stream.next(m.zf);
      stream.next(m.vmax);
      stream.next(m.amax);
      stream.next(m.gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct linear_speed_xyz_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_delta_robot::linear_speed_xyz_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_delta_robot::linear_speed_xyz_<ContainerAllocator>& v)
  {
    s << indent << "xo: ";
    Printer<float>::stream(s, indent + "  ", v.xo);
    s << indent << "yo: ";
    Printer<float>::stream(s, indent + "  ", v.yo);
    s << indent << "zo: ";
    Printer<float>::stream(s, indent + "  ", v.zo);
    s << indent << "xf: ";
    Printer<float>::stream(s, indent + "  ", v.xf);
    s << indent << "yf: ";
    Printer<float>::stream(s, indent + "  ", v.yf);
    s << indent << "zf: ";
    Printer<float>::stream(s, indent + "  ", v.zf);
    s << indent << "vmax: ";
    Printer<float>::stream(s, indent + "  ", v.vmax);
    s << indent << "amax: ";
    Printer<float>::stream(s, indent + "  ", v.amax);
    s << indent << "gripper: ";
    Printer<int64_t>::stream(s, indent + "  ", v.gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DELTA_ROBOT_MESSAGE_LINEAR_SPEED_XYZ_H
