// Generated by gencpp from file my_delta_robot/num_point.msg
// DO NOT EDIT!


#ifndef MY_DELTA_ROBOT_MESSAGE_NUM_POINT_H
#define MY_DELTA_ROBOT_MESSAGE_NUM_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_delta_robot
{
template <class ContainerAllocator>
struct num_point_
{
  typedef num_point_<ContainerAllocator> Type;

  num_point_()
    : num_point_1(0)
    , num_point_2(0)  {
    }
  num_point_(const ContainerAllocator& _alloc)
    : num_point_1(0)
    , num_point_2(0)  {
  (void)_alloc;
    }



   typedef int64_t _num_point_1_type;
  _num_point_1_type num_point_1;

   typedef int64_t _num_point_2_type;
  _num_point_2_type num_point_2;





  typedef boost::shared_ptr< ::my_delta_robot::num_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_delta_robot::num_point_<ContainerAllocator> const> ConstPtr;

}; // struct num_point_

typedef ::my_delta_robot::num_point_<std::allocator<void> > num_point;

typedef boost::shared_ptr< ::my_delta_robot::num_point > num_pointPtr;
typedef boost::shared_ptr< ::my_delta_robot::num_point const> num_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_delta_robot::num_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_delta_robot::num_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_delta_robot::num_point_<ContainerAllocator1> & lhs, const ::my_delta_robot::num_point_<ContainerAllocator2> & rhs)
{
  return lhs.num_point_1 == rhs.num_point_1 &&
    lhs.num_point_2 == rhs.num_point_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_delta_robot::num_point_<ContainerAllocator1> & lhs, const ::my_delta_robot::num_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_delta_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_delta_robot::num_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_delta_robot::num_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_delta_robot::num_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_delta_robot::num_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_delta_robot::num_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_delta_robot::num_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_delta_robot::num_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f69ff62ad97702372d7a82c71cf0ac27";
  }

  static const char* value(const ::my_delta_robot::num_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf69ff62ad9770237ULL;
  static const uint64_t static_value2 = 0x2d7a82c71cf0ac27ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_delta_robot::num_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_delta_robot/num_point";
  }

  static const char* value(const ::my_delta_robot::num_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_delta_robot::num_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num_point_1\n"
"int64 num_point_2\n"
;
  }

  static const char* value(const ::my_delta_robot::num_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_delta_robot::num_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_point_1);
      stream.next(m.num_point_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_delta_robot::num_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_delta_robot::num_point_<ContainerAllocator>& v)
  {
    s << indent << "num_point_1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num_point_1);
    s << indent << "num_point_2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num_point_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DELTA_ROBOT_MESSAGE_NUM_POINT_H
